### ISSUE TITLE
Identifiable class

### ISSUE THREAD

**Issue by charlieguo2021** [CSC207-UofT/course-project-codemonkeys#28]
After reviewing our current codebase, I found that identifiable is an abstract class, not an interface. Would it be better if we change identifiable to an interface?

**Comment by Vim0315** [comment]
The abstract class could be better because the constructors are constant among all identifiable classes.

**Comment by RaymondZhang24** [comment]
I think we should leave it as an abstract class

**Comment by langsonzhang** [comment]
The reason I wrote it as an abstract class is so you can inherit the methods without having to implement them in each subclass. Writing it as an interface is a possibility, but then we would have to implement the same methods in each subclass. The only downside I think for the abstract class implementation is that you can only extend one class in java, but I think this is not that big of a problem and can be worked around. If you have a specific example as to why the interface implementation may be better, please share.

**Comment by Edward11235** [comment]
I agree with Langson. If we make identifiable an interface instead of an abstract class, when we implement the methods in identifiable, we write repetitive code since many behaviours are similar.
By using abstract class, we can avoid writing repetitive codes.
