### ISSUE TITLE
Do we need to store the number of upvotes and downvotes in Vote class? Would a transaction be executed if a vote is passed?

### ISSUE THREAD

**Issue by Vim0315** [CSC207-UofT/course-project-codemonkeys#31]

**Comment by langsonzhang** [comment]
From my understanding of the Vote class, we do not. Instead, it is the VoteManager's job to store all of the votes for each transaction and judge whether or not a Transaction will be executed.

**Comment by RaymondZhang24** [comment]
Yes, Vote is a class that could be classified into upvotes and downvotes. It is Votemanagers job to determine the excutition.
