### ISSUE TITLE
How the user classes works have been changed. Please see the comment for details.

### ISSUE THREAD

**Issue by Vim0315** [CSC207-UofT/course-project-codemonkeys#32]
When creating an ordinary user(with no authorities), create a CommonUser object.
When granting ban authority to a user, do `user = new BanAuthority(user)`.
It is the same when granting control vote authority.

In addition, a Check_Authority method has been added. One can use it to check if the user has a certain authority.
For example, `user.Check_Authority("Ban")` returns true if the user has ban authority, and returns false otherwise.

The usage of Users in higher layers needs to be changed. Please feel free to contact me if you have any concerns/suggestions.

**Comment by langsonzhang** [comment]
What if we had User store an instance of UserAuthority as a variable? This way, we can simply check a User's authority by
"user.getAuthority() instanceof BanAuthority" instead of relying on a String, which is more prone to typos which might cause accidental bugs.

**Comment by Vim0315** [comment]
> 

This would work but what if a user has multiple authorities?

**Comment by langsonzhang** [comment]
Right. But I don't see how our current solution handles that either. If I understood correctly, authorities extend UserAuthority which extends User, which means an instance of BanAuthority is itself a User. Then how do I check if this user "has" VoteAuthority?

**Comment by Vim0315** [comment]
> 

Each UserAuthority takes an `authorized_user`, and the `Check_Authority` method first checks if this `authorized_user` has the authority. Let's say if we have `User user = new BanAuthority(new ControlVoteAuthority(new CommonUser('Vim')));`, `user.Check_Authority("Vote")` would idealy return true.

**Comment by langsonzhang** [comment]
I see. But in the case you gave, how would the user.checkAuthority(“ban”) call return whether or not the user has “ban” authority?

**Comment by Vim0315** [comment]
It's also going to return true. I have included a test case for this in test files.

**Comment by langsonzhang** [comment]
I see. But making a User every time we add an authority seems necessary to me. If we are constructing nested Users, then how do we plan on removing authorities? Say I have

User user = new VoteAuthority(new BanAuthority( new User()));

and I want to remove BanAuthority, how do I do it? I like the idea of authorities, but I think the recursive implementation we currently have is very limiting.

**Comment by Vim0315** [comment]
You are right Langston. It is also causing problems in UUIDs. I will consider refactoring it.
