### ISSUE TITLE
What happens to the user's UUID when we give him a new authority? 

### ISSUE THREAD

**Issue by Vim0315** [CSC207-UofT/course-project-codemonkeys#41]
Should it change or remain unchanged?

**Comment by langsonzhang** [comment]
In my opinion it should stay the same since the user is still the same. What specific scenario are you thinking about?

**Comment by JackSunjm** [comment]
When we give a common user Authorities, we are actually creating a new user, so in this case the id will change.

**Comment by Vim0315** [comment]
> In my opinion it should stay the same since the user is still the same. What specific scenario are you thinking about?

Yes, Jack is right, and if we want it to remain the same then we might need methods to set and get UUIDs.
Or we can rewrite the User related classes, which would be a lot more work.

**Comment by Vim0315** [comment]
Decided to make it stay the same after giving new authority.
